chore(hapi): database persistence of blockchain events
eoscostarica/eosio-spend-explorer pull request #46
Opened 2022-08-08 15:57 UTC by warnerHurtado

### Database persistence of blockchain events

### What does this PR do?

- Resolve #30 

### Steps to test

1. Run the project
2. Go to the folder hapi/src/services/hyperion/index and see the changes
3. Go to the folder hapi/src/services/hyperion/updaters and see the changes on eosiotoken and genesiseden

#### CheckList

- [x] Follow proper Markdown format
- [x] The content is adequate
- [x] The content is available in both english and spanish
- [x] I Ran a spell check

2022-08-08 22:23 UTC, xavier506 commented on hapi/src/services/hyperion/updaters/eosiotoken-transfer.updater.js
> +        type: 'income'   //TODO: ASK FOR THIS ONE
lets remove the comments

2022-08-08 22:23 UTC, xavier506 commented on hapi/src/services/hyperion/updaters/genesiseden-withdraw.updater.js
> +        type: 'expense' //TODO: ASK FOR THIS ONE
remove comments

2022-08-08 22:53 UTC, leisterfrancisco commented on hapi/src/services/hyperion/index.js
remove blank line

2022-08-08 22:53 UTC, leisterfrancisco commented on hapi/src/services/hyperion/index.js
remove blank line

2022-08-08 22:53 UTC, leisterfrancisco commented on hapi/src/services/hyperion/index.js
> +
remove blank line

2022-08-08 22:55 UTC, leisterfrancisco requested changes

2022-08-08 22:55 UTC, leisterfrancisco commented on hapi/src/services/hyperion/index.js
clean code: remove blank line

2022-08-08 22:55 UTC, leisterfrancisco commented on hapi/src/services/hyperion/index.js
> +      ; ({ hasMore, actions } = await getActions({ after, before, skip }))
why?

2022-08-08 22:55 UTC, leisterfrancisco commented on hapi/src/services/hyperion/updaters/genesiseden-withdraw.updater.js
> +      console.log(action);
is this console log necessary?

2022-08-08 22:55 UTC, leisterfrancisco commented on hapi/src/services/hyperion/updaters/genesiseden-withdraw.updater.js
> +
remove blank line

2022-08-09 20:13 UTC, warnerHurtado commented
Requested changes fixed.

2022-08-09 20:17 UTC, xavier506 commented
> This pull request **fixes 1 alert** when merging [afc0f81](https://github.com/eoscostarica/eosio-spend-explorer/commit/afc0f81ca611b1c6250a9a369b561c1f9b7294f5) into [9cce1c3](https://github.com/eoscostarica/eosio-spend-explorer/commit/9cce1c31e6e95f25b07afc671659a67421370906) - [view on LGTM.com](https://lgtm.com/projects/g/eoscostarica/eosio-spend-explorer/rev/pr-15fe271ef679aff9fceedf10a99167aaeed09862)
> 
> **fixed alerts:**
> 
> * 1 for Unused variable, import, function or class

@warnerHurtado  please check

![image](https://user-images.githubusercontent.com/5632966/183752591-5309a782-8152-44d7-9c25-7820f596a102.png)

2022-08-09 20:18 UTC, xavier506 approved these changes
LGTM

2022-08-09 20:41 UTC, merged