feat(webapp): add table and graph for income
eoscostarica/eosio-spend-explorer pull request #63
Opened 2022-08-24 21:50 UTC by warnerHurtado

### Add table and graph for income

### What does this PR do?

- Resolve #47 

### Steps to test

1. run the project
2. go to the sidebar and click on income
3. See the view

#### CheckList

- [] Follow proper Markdown format
- [] The content is adequate
- [] The content is available in both english and spanish
- [] I Ran a spell check

2022-08-24 22:02 UTC, leisterfrancisco requested changes

2022-08-24 22:02 UTC, leisterfrancisco commented on webapp/src/routes/IncomeReport/styles.js
> +      // margin: '16px 31.6px 3px 318px',
do we need this comment?

2022-08-24 22:02 UTC, leisterfrancisco commented on webapp/src/routes/IncomeReport/styles.js
> +    // margin: 0 0 27.1px 99.6px;
do we need this comment?

2022-08-24 22:02 UTC, leisterfrancisco commented on webapp/src/routes/IncomeReport/styles.js
> +    // margin: 15.5px 0.3px 1.5px 47.3px;
do we need this comment?

2022-08-24 22:02 UTC, leisterfrancisco commented on webapp/src/routes/IncomeReport/styles.js
> +    // margin: 1.5px 0.6px 0 0;
do we need this comment?

2022-08-24 22:02 UTC, leisterfrancisco commented on webapp/src/routes/IncomeReport/styles.js
> +    // margin: 1.5px 0.6px 0 0;
do we need this comment?

2022-08-24 22:02 UTC, leisterfrancisco commented on webapp/src/routes/index.js
> +  Home as GridIcon,
shouldn't we rename it as HomeIcon?

2022-08-25 02:30 UTC, tetogomez approved these changes
LGTM

2022-08-25 03:01 UTC, leisterfrancisco approved these changes

2022-08-25 04:24 UTC, merged