feat(webapp): improve UI from main page
eoscostarica/eosio-spend-explorer pull request #78
Opened 2022-09-02 22:22 UTC by warnerHurtado

### Title

### What does this PR do?

- Resolve #53 

### Steps to test

1. run the project and open localhost:3000 in your browser
2. click on income in the sidebar and see new features

#### CheckList
- [] Follow proper Markdown format
- [] The content is adequate
- [] The content is available in both english and spanish
- [] I Ran a spell check

2022-09-02 23:19 UTC, xavier506 commented on webapp/src/components/Footer/index.js
> +          <Box className={classes.footerInformation}>
should we be using divs instead of box here?

2022-09-02 23:20 UTC, xavier506 commented on webapp/src/language/es.json
> +    "subTitle": "Ingresos por delegados",
Should it be: Ingresos por delegado (singluar). ?

2022-09-03 00:19 UTC, tetogomez requested changes
Please Remove Box and Grid from the whole PR

2022-09-03 00:19 UTC, tetogomez commented on webapp/src/components/Footer/index.js
> +import { Grid, Box } from '@mui/material'
according MUI docs this kind of import components `import Box from '@mui/material/Box'` is better than `import { Grid, Box } from '@mui/material'`
Please import de component directly.

Actually we are avoiding use Box and Grid components in order to keep up the performance

2022-09-03 00:19 UTC, tetogomez commented on webapp/src/components/Footer/index.js
>      </Box>
Refactor this component and remove Box and Grid

2022-09-03 00:19 UTC, tetogomez commented on webapp/src/components/Header/index.js
> +          </Box>
same in this file

2022-09-03 03:23 UTC, xavier506 reviewed
are you sure you want to delete 
`hapi/src/services/hyperion/updaters/genesis-fundtransfer.updater.js`
and 
`hasura/seeds/default/1661533517069_initialEdenHistoricElectionSeed.sql`

?

2022-09-03 05:30 UTC, JAMares commented
The files deleted are by my recommendation, these are unused files that deleted on my PR, but both there were when created this branch

2022-09-05 02:55 UTC, xavier506 commented on webapp/src/components/Footer/index.js
> +              src="https://guias.eoscostarica.io/assets/images/eoscostarica-logo-790106817dcb2928ca190a0723d48662.png"
this image should be stored in the `webapp/static/` folder

2022-09-05 02:56 UTC, xavier506 commented on webapp/src/components/Footer/index.js
> +                Linkedin
LinkedIn (capital I)

2022-09-05 02:57 UTC, xavier506 commented on webapp/src/components/Footer/index.js
> +              <a href="https://edeneos.org/">Website EOS Costa Rica</a>
this is not the eos costa rica website URL

2022-09-05 02:57 UTC, xavier506 commented on webapp/src/components/Footer/index.js
> +              <a href="https://www.linkedin.com/company/eoscostarica/mycompany/">
https://www.linkedin.com/company/eoscostarica

2022-09-05 03:00 UTC, xavier506 commented on webapp/src/components/Header/index.js
> +              src={process.env.PUBLIC_URL + '/EOS-Spend-Explorer.png'}
we should keep images in `webapp/static/images` folder

2022-09-05 03:38 UTC, xavier506 commented on webapp/src/routes/IncomeReport/index.js
> +              Next disbursement date: June 8, 2022
This date needs to be sourced from the chain tables. we can create a new issue for this

2022-09-06 21:28 UTC, tetogomez requested changes
Just one comment more

2022-09-06 21:28 UTC, tetogomez commented on webapp/src/routes/IncomeReport/IncomeChart.js
> +    <ul style={{ listStyle: 'none', overflowY: 'auto', maxHeight: '400px' }}>
Aviod to use inline style, create a class and use classes const

2022-09-07 01:18 UTC, leisterfrancisco requested changes

2022-09-07 01:18 UTC, leisterfrancisco commented on webapp/src/layouts/Dashboard/index.js
> +import { Toolbar } from '@mui/material'
please, import it in top of this file.

import order:
1. Third-party libraries
2. Project import
3. Folder import

2022-09-07 01:28 UTC, tetogomez approved these changes
LGTM

2022-09-07 03:43 UTC, xavier506 approved these changes
LGTM

2022-09-07 03:43 UTC, merged